name: simple_record_app_riverpod
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  flutter_screenutil: ^5.9.3
  l: ^5.0.0
  flutter_svg: ^2.0.16

  path: ^1.9.0
  path_provider: ^2.1.5

  record: ^5.2.0
  just_audio: ^0.9.42

  flutter_native_splash: ^2.4.1
  share_plus: ^10.1.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
